"""COUP Drone Alpha: constrained project compiler and honest SITL evidence runner."""

from __future__ import annotations

import asyncio
import hashlib
import json
import os
import py_compile
import subprocess
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

SCHEMA_VERSION = "coup.dev/v1alpha1"
PX4_VERSION = "v1.17.0"
MAVSDK_VERSION = "3.17.2"
SCENARIO_VERSION = "drone-alpha-scenario-v1"
UNSUPPORTED_TERMS = ("weapon", "target", "explosive", "payload release", "evasion")


class DroneScopeError(ValueError):
    pass


@dataclass(frozen=True)
class DroneSpec:
    name: str
    mission: str
    environment: str
    stability: str
    responsiveness: str
    gps: bool = True
    camera: bool = True
    return_home: bool = True
    safety_profile: str = "conservative"

    def to_dict(self) -> dict[str, Any]:
        return {
            "apiVersion": SCHEMA_VERSION,
            "kind": "Drone",
            "metadata": {"name": self.name},
            "platform": {"profile": "coup-quad-alpha", "family": "quad"},
            "mission": {"type": self.mission},
            "behavior": {"stability": self.stability, "responsiveness": self.responsiveness},
            "environment": {"type": self.environment},
            "capabilities": {"gps": self.gps, "camera": self.camera, "return_home": self.return_home},
            "safety": {"profile": self.safety_profile},
        }


def _digest(value: object) -> str:
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def _contains(text: str, terms: tuple[str, ...]) -> bool:
    lowered = text.lower()
    return any(term in lowered for term in terms)


def compile_intent(intent: str, previous: DroneSpec | None = None) -> DroneSpec:
    if _contains(intent, UNSUPPORTED_TERMS):
        raise DroneScopeError("COUP Drone Alpha supports only benign civilian inspection and testing.")
    lowered = intent.lower()
    if not any(word in lowered for word in ("drone", "quad", "inspect", "farm", "indoor", "stable", "responsive")):
        raise DroneScopeError("Drone Alpha supports only quadrotor inspection intents and bounded behavior changes.")
    base = previous or DroneSpec("scout", "inspection", "outdoor", "high", "low")
    environment = "indoor" if _contains(lowered, ("indoor", "inside")) else "outdoor" if _contains(lowered, ("outdoor", "farm", "field")) else base.environment
    stability = "high" if _contains(lowered, ("stable", "easy to fly", "easier", "conservative")) else base.stability
    responsiveness = "high" if _contains(lowered, ("responsive", "faster response", "agile")) else "low" if _contains(lowered, ("less responsive", "gentle")) else base.responsiveness
    return DroneSpec(base.name, "inspection", environment, stability, responsiveness)


def _yaml(spec: DroneSpec) -> str:
    values = spec.to_dict()
    return "\n".join(
        [
            f"apiVersion: {values['apiVersion']}", "kind: Drone", "metadata:", f"  name: {spec.name}",
            "platform:", "  profile: coup-quad-alpha", "  family: quad", "mission:", "  type: inspection",
            "behavior:", f"  stability: {spec.stability}", f"  responsiveness: {spec.responsiveness}",
            "environment:", f"  type: {spec.environment}", "capabilities:", "  gps: true", "  camera: true", "  return_home: true",
            "safety:", "  profile: conservative", "",
        ]
    )


def parameter_overlay(spec: DroneSpec) -> str:
    # These bounded PX4 parameters only express Alpha presets; users never supply raw values.
    values = {
        "MPC_ACC_HOR": "2.0" if spec.stability == "high" else "3.0",
        "MPC_TILTMAX_AIR": "25" if spec.stability == "high" else "35",
        "MPC_XY_CRUISE": "3.0" if spec.responsiveness == "low" else "5.0",
        "MPC_XY_VEL_MAX": "5.0" if spec.responsiveness == "low" else "8.0",
    }
    return "# Generated by COUP Drone Alpha. Apply only to PX4 v1.17.0 sihsim_quadx.\n" + "\n".join(f"{key}\t{value}" for key, value in values.items()) + "\n"


def mission_source(spec: DroneSpec) -> str:
    return f'''"""Generated COUP mission metadata for {spec.name}; execution is performed by the verified scenario runner."""
MISSION = {{"type": "inspection", "environment": "{spec.environment}", "return_home": True}}
'''


def scenario_definition(spec: DroneSpec) -> str:
    """A checked-in, generated scenario contract for the MAVSDK runner."""
    return "\n".join(
        [
            "name: conservative-inspection-flight",
            "version: " + SCENARIO_VERSION,
            "vehicle: sihsim_quadx",
            "steps:",
            "  - vehicle_discovery",
            "  - health_preflight",
            "  - arm",
            "  - takeoff",
            "  - hover",
            "  - land",
            "assertions:",
            "  minimum_hover_altitude_m: 0.5",
            "  physical_flight: not_verified",
            "",
        ]
    )


def project_root(path: Path) -> Path:
    return path.resolve()


def state_path(root: Path) -> Path:
    return root / ".coup" / "state.json"


def load_state(root: Path) -> dict[str, Any]:
    path = state_path(root)
    if not path.exists():
        raise DroneScopeError("Not a COUP project. Run `coup init` first.")
    return json.loads(path.read_text(encoding="utf-8"))


def save_state(root: Path, state: dict[str, Any]) -> None:
    state_path(root).parent.mkdir(parents=True, exist_ok=True)
    state_path(root).write_text(json.dumps(state, indent=2), encoding="utf-8")


def init_project(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)
    (root / "coup.yaml").write_text("name: scout\nprofile: coup-quad-alpha\n", encoding="utf-8")
    save_state(root, {"project": "scout", "profile": "coup-quad-alpha", "builds": []})


def create_version(root: Path, intent: str) -> dict[str, Any]:
    state = load_state(root)
    parent = state["builds"][-1] if state["builds"] else None
    previous = DroneSpec(**parent["spec"]) if parent else None
    spec = compile_intent(intent, previous)
    number = len(state["builds"]) + 1
    build_id = f"{number:04d}"
    build_root = root / "builds" / build_id / "coup-drone"
    for directory in ("drone/configuration", "drone/parameters", "autopilot/overlay", "app", "missions", "tests/scenarios", "build", "verification"):
        (build_root / directory).mkdir(parents=True, exist_ok=True)
    spec_file = build_root / "drone/spec.yaml"
    overlay = build_root / "autopilot/overlay/coup_quad_alpha.params"
    source = build_root / "app/mission.py"
    scenario = build_root / "tests/scenarios/conservative_inspection.yaml"
    spec_file.write_text(_yaml(spec), encoding="utf-8")
    overlay.write_text(parameter_overlay(spec), encoding="utf-8")
    source.write_text(mission_source(spec), encoding="utf-8")
    scenario.write_text(scenario_definition(spec), encoding="utf-8")
    lock = {"coup_compiler": "drone-alpha-v1", "drone_spec": SCHEMA_VERSION, "px4": PX4_VERSION, "vehicle": "sihsim_quadx", "mavsdk_python": MAVSDK_VERSION, "scenario_suite": SCENARIO_VERSION}
    (build_root / "coup.lock").write_text(json.dumps(lock, indent=2) + "\n", encoding="utf-8")
    manifest = {"intent": intent, "parent_build": parent["id"] if parent else None, "drone_spec_hash": _digest(spec.to_dict()), "overlay_hash": _digest(overlay.read_text(encoding="utf-8")), "scenario_hash": _digest(scenario.read_text(encoding="utf-8")), "lock_hash": _digest(lock)}
    (build_root / "drone/manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    record = {"id": build_id, "parent": parent["id"] if parent else None, "intent": intent, "spec": asdict(spec), "root": str(build_root), "manifest": manifest, "build": "not_run", "test": "not_run"}
    state["builds"].append(record)
    save_state(root, state)
    return record


def build_version(root: Path, build_id: str | None = None) -> dict[str, Any]:
    state = load_state(root)
    record = next((item for item in state["builds"] if item["id"] == (build_id or state["builds"][-1]["id"])), None)
    if not record:
        raise DroneScopeError("Build not found.")
    build_root = Path(record["root"])
    started = time.perf_counter()
    try:
        py_compile.compile(str(build_root / "app/mission.py"), cfile=str(build_root / "build/mission.pyc"), doraise=True)
        result = {"status": "passed", "command": "python -m py_compile app/mission.py", "duration_ms": round((time.perf_counter() - started) * 1000)}
    except Exception as exc:
        result = {"status": "failed", "error": f"{type(exc).__name__}: {exc}", "duration_ms": round((time.perf_counter() - started) * 1000)}
    record["build"] = result["status"]
    (build_root / "build/result.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    save_state(root, state)
    return record


async def _mavsdk_scenario(endpoint: str, report: dict[str, Any]) -> None:
    from mavsdk import System

    drone = System()
    await drone.connect(system_address=endpoint)
    async for connection in drone.core.connection_state():
        if connection.is_connected:
            report["vehicle_discovery"] = "passed"
            break
    async for health in drone.telemetry.health():
        report["health"] = {"global_position_ok": health.is_global_position_ok, "home_position_ok": health.is_home_position_ok}
        break
    await drone.action.arm()
    report["arming"] = "passed"
    await drone.action.takeoff()
    report["takeoff"] = "commanded"
    await asyncio.sleep(8)
    async for position in drone.telemetry.position():
        report["hover"] = {"relative_altitude_m": position.relative_altitude_m}
        if position.relative_altitude_m < 0.5:
            raise RuntimeError("Hover altitude was below the scenario minimum.")
        report["hover"]["status"] = "passed"
        break
    await drone.action.land()
    report["landing"] = "commanded"
    async for in_air in drone.telemetry.in_air():
        if not in_air:
            report["landing"] = "passed"
            return


def _start_launcher(command: str, log_path: Path) -> subprocess.Popen[str]:
    log_file = log_path.open("w", encoding="utf-8")
    process = subprocess.Popen(command, shell=True, stdout=log_file, stderr=subprocess.STDOUT, text=True)
    process._coup_log_file = log_file  # type: ignore[attr-defined]
    return process


def test_version(
    root: Path,
    build_id: str | None = None,
    endpoint: str = "udpin://0.0.0.0:14540",
    launcher: str | None = None,
) -> dict[str, Any]:
    state = load_state(root)
    record = next((item for item in state["builds"] if item["id"] == (build_id or state["builds"][-1]["id"])), None)
    if not record:
        raise DroneScopeError("Build not found.")
    build_root = Path(record["root"])
    report: dict[str, Any] = {
        "status": "unavailable",
        "stack": {"px4": PX4_VERSION, "mavsdk_python": MAVSDK_VERSION, "endpoint": endpoint},
        "physical_flight": "not_verified",
        "limitations": ["SIH/SITL evidence does not verify physical flight."],
        "tests_executed": [],
    }
    if record["build"] != "passed":
        report["reason"] = "Run `coup build` successfully before testing."
    elif not (launcher or os.getenv("COUP_PX4_SITL_COMMAND")):
        report["reason"] = (
            "No pinned PX4 SITL launcher was supplied. Set COUP_PX4_SITL_COMMAND or pass --launcher; "
            "COUP will not use an unpinned latest image as verification evidence."
        )
    else:
        command = launcher or os.environ["COUP_PX4_SITL_COMMAND"]
        log_path = build_root / "verification/sitl.log"
        process: subprocess.Popen[str] | None = None
        started = time.perf_counter()
        try:
            process = _start_launcher(command, log_path)
            time.sleep(4)
            if process.poll() is not None:
                raise RuntimeError(f"PX4 SITL launcher exited with code {process.returncode}.")
            report["tests_executed"] = ["vehicle_discovery", "health_preflight", "arm", "takeoff", "hover", "land"]
            asyncio.run(asyncio.wait_for(_mavsdk_scenario(endpoint, report), timeout=90))
            report["status"] = "passed"
            report["duration_ms"] = round((time.perf_counter() - started) * 1000)
        except Exception as exc:
            report["status"] = "failed"
            report["error"] = f"{type(exc).__name__}: {exc}"
            report["duration_ms"] = round((time.perf_counter() - started) * 1000)
        finally:
            if process and process.poll() is None:
                process.terminate()
                try:
                    process.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    process.kill()
            if process and hasattr(process, "_coup_log_file"):
                process._coup_log_file.close()  # type: ignore[attr-defined]
        report["evidence"] = {"sitl_log": str(log_path), "scenario": "tests/scenarios/conservative_inspection.yaml"}
    (build_root / "verification/report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    record["test"] = report["status"]
    save_state(root, state)
    return record
